vich_uploader:
    db_driver: orm

    mappings:
        picture:
           uri_prefix: '%app.path.picture%'
           upload_destination: '%pics_directory%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           delete_on_remove: true
           delete_on_update: true
